// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtkvb2sdlwmMZn331JkynhfMc2myk7yqA',
    appId: '1:977992917954:web:8025ad2f0c19bde8892c5b',
    messagingSenderId: '977992917954',
    projectId: 'test-database-gtr',
    authDomain: 'test-database-gtr.firebaseapp.com',
    storageBucket: 'test-database-gtr.firebasestorage.app',
    measurementId: 'G-G4X77WKCQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMj9QL6NGvncsarZRhLmFLx7sYOt8EvRo',
    appId: '1:977992917954:android:c496d398614560fc892c5b',
    messagingSenderId: '977992917954',
    projectId: 'test-database-gtr',
    storageBucket: 'test-database-gtr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtT8xLF9jXkaSkd_tcyPiy_lmYPA-Cmh0',
    appId: '1:977992917954:ios:d2a05f28dc54784f892c5b',
    messagingSenderId: '977992917954',
    projectId: 'test-database-gtr',
    storageBucket: 'test-database-gtr.firebasestorage.app',
    iosBundleId: 'com.example.project001',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtT8xLF9jXkaSkd_tcyPiy_lmYPA-Cmh0',
    appId: '1:977992917954:ios:d2a05f28dc54784f892c5b',
    messagingSenderId: '977992917954',
    projectId: 'test-database-gtr',
    storageBucket: 'test-database-gtr.firebasestorage.app',
    iosBundleId: 'com.example.project001',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtkvb2sdlwmMZn331JkynhfMc2myk7yqA',
    appId: '1:977992917954:web:df7b0f96f1be91cc892c5b',
    messagingSenderId: '977992917954',
    projectId: 'test-database-gtr',
    authDomain: 'test-database-gtr.firebaseapp.com',
    storageBucket: 'test-database-gtr.firebasestorage.app',
    measurementId: 'G-4H5E6EMSRY',
  );
}
